spring:
  datasource:
    url: jdbc:mysql://localhost/hotelApiRest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS

springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger-ui.html
springdoc.swagger-ui.enabled: true

SONAR_TOKEN:  a6efc9bc8e7e5c5f45bba428f9100c9a8c00aa18